### ISSUE TITLE
Is anyone supporting this library?

### ISSUE THREAD

**Issue by helenwilliamson** [guidesmiths/marv-pg-driver#24]
Hi,

Wondered if anyone is actively supporting this library as there are a number of deoendency version bumps that haven't been done that are over 1.5 years old.

Thanks

**Comment by cressie176** [comment]
Hi @helenwilliamson,

Yes, it's still maintained. As to the number of outstanding PRs, if you think about what marv does, and how it's used, there's almost no chance of 3rd party library causing a genuine vulnerability, so they tend to build up until there's a good reason to release a new version. Questions (like this one), feature requests and bug fixes are dealt with promptly.

Kind regards,

Steve
