### ISSUE TITLE
Interop with marv 3.x

### ISSUE THREAD

**Issue by ctavan** [guidesmiths/marv-pg-driver#6]
marv-pg-driver lists `marv@^2.4.1` as a direct dependency.

https://github.com/guidesmiths/marv-pg-driver/blob/ec5135835da7a6261cd32cafc6f57aaa9e555980/package.json#L30

Wouldn't it be more appropriate to specify `marv` as a `peerDependency` to improve interoperability with different versions of `marv`?

Right now there doesn't seem to be a reasonable way of using `marv@3.x` with `marv-pg-driver@2.x` (the latest respective versions).

**Comment by cressie176** [comment]
Hi @ctavan,
Thanks for reporting this. Will fix promptly.

**Comment by cressie176** [comment]
I've managed to remove the production dependency on marv all together (although it's still needed for tests). Can you try the following and advise if it fixes the issue for you please?

```
npm i marv@latest
npm i marv-pg-driver@latest
```

**Comment by cressie176** [comment]
Any luck?

**Comment by ctavan** [comment]
Works for me with `marv-pg-driver@^3.0.0`, thank you so much!
